import "./fonts/Lato/lato.css";
import "../node_modules/font-awesome/css/font-awesome.min.css";


import "jquery";
import "../scripts/jquery-ui-1.12.1.custom/jquery-ui.min.js";
import "../scripts/jquery-ui-1.12.1.custom/jquery-ui.min.css";
import "../node_modules/css-ripple-effect/dist/ripple.min.css";
import "../node_modules/select2/dist/js/select2.min.js";
import "../node_modules/select2/dist/css/select2.min.css";
import "../node_modules/gmap3/dist/gmap3.min.js";
import "../node_modules/jquery-ui-slider-pips/dist/jquery-ui-slider-pips.min.js"
import "../node_modules/jquery-ui-slider-pips/dist/jquery-ui-slider-pips.min.css"
import "jquery-circle-progress";


import "./pages/index/index.styl";
import "./pages/page-template/page-template.styl";
import "./blocks/header/header.styl";
import "./blocks/header/header.js";
import "./blocks/search/search.styl";
import "./blocks/video/video.styl";
import "./pages/videos/videos.styl";
import "./pages/videos/videos.js";
import "./blocks/standard-button/standard-button.styl";
import "./blocks/dropdown/dropdown.styl";
import "./blocks/dropdown/dropdown.js";
import "./pages/news/news.styl";
import "./blocks/news-item/news-item.styl";
import "./blocks/arrow-button/arrow-button.styl";
import "./blocks/event/event.styl";
import "./blocks/tick-box/tick-box.styl";
import "./pages/events/events.styl";
import "./pages/events/events.js";
import "./blocks/toggle/toggle.styl";
import "./blocks/toggle/toggle.js";
import "./blocks/location/location.styl";
import "./blocks/location/location.js";
import "./blocks/location/img/map-marker-icon.png";
import "./blocks/user-profile/user-profile.styl";
import "./blocks/user-profile/img/user-profile-woman.png";
import "./blocks/user-profile/img/user-profile-man.png";
import "./blocks/slider/slider.styl";
import "./blocks/slider/slider.js";
import "./blocks/calendar/calendar.styl";
import "./blocks/calendar/calendar.js";
import "./pages/articles/articles.styl";
import "./pages/articles/articles.js";
import "./blocks/percentage/percentage.styl";
import "./blocks/percentage/percentage.js";
import "./blocks/stages/stages.styl";
import "./blocks/stages/stages.js";
import "./pages/event-new/event-new.styl";
import "./pages/event-new/event-new.js";
import "./pages/sign-in/sign-in.styl";
import "./pages/sign-up/sign-up.styl";
import "./blocks/categories-navigation/categories-navigation.styl";
import "./blocks/horizontal-preview-section/horizontal-preview-section.styl";
import "./blocks/section-title/section-title.styl";